- hosts: all
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose-v2
        state: present

    - name: Ensure Docker is started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy docker-compose.yml to EC2
      copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/app/docker-compose.yml
        mode: '0644'

    - name: Copy prometheus.yml to EC2
      copy:
        src: ./prometheus.yml
        dest: /home/ubuntu/app/prometheus.yml
        mode: '0644'

    - name: Stop existing containers
      shell: docker compose down
      args:
        chdir: /home/ubuntu/app
      ignore_errors: yes

    - name: Pull latest petclinic image
      shell: docker pull yanasheva/petclinic:latest

    - name: Run docker compose
      shell: docker compose up -d
      args:
        chdir: /home/ubuntu/app
